// Carries the tooling audit tables across from the hub's source file into
// content/ai-tooling-audit.md, cleared for a public surface. One direction
// only: this script reads the hub and writes here, never the reverse. To
// re-audit, edit the hub file, run `npm run sync`, and commit the result.
// Anything not cleared for the page (source citations, hub issue numbers,
// the stack behind "database-backed") is stripped mechanically here so it
// cannot be retyped by hand.
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';

const HUB = process.env.HUB_DIR || '/Users/jamie/Dev/project_job';
const SOURCE = path.join(HUB, 'data', 'ai-tooling-audit.md');
const ROOT = path.resolve(import.meta.dirname, '..');
const OUT = path.join(ROOT, 'content', 'ai-tooling-audit.md');

const src = await readFile(SOURCE, 'utf8').catch(() => {
  console.error(`Cannot read ${SOURCE}. Set HUB_DIR to the hub checkout, or ask Jamie.`);
  process.exit(1);
});

const audited = src.match(/\*\*Last audited: ([^.*]+)\.\*\*/)?.[1];
if (!audited) throw new Error('no "Last audited" line in source');

// Pull the table under a given heading as rows of cells.
function table(heading) {
  const start = src.indexOf(`\n## ${heading}\n`);
  if (start < 0) throw new Error(`no section "${heading}"`);
  const body = src.slice(start + 1).split(/\n## /)[0];
  const lines = body.split('\n').filter((l) => l.startsWith('|'));
  const rows = lines.map((l) => l.slice(1, -1).split(' | ').map((c) => c.trim()));
  return { header: rows[0], rows: rows.slice(2) };
}

// Public-surface clearance. Each rule is named so a future reader can see
// what was removed and why.
const clear = (text) => text
  .replace(/\s*\(Stack is Notion\.[^)]*\)/g, '')       // the stack stays private
  .replace(/Notion/g, 'database-backed via MCP')       // naming rule
  .replace(/\s*\(issue #\d+\)/g, '')                   // hub issue numbers mean nothing here
  .replace(/NO NAMES on purpose: /g, '')               // editorial note, not copy
  .replace(/\bSep\b/g, 'Sept');                        // house style: September is Sept, the rest are three letters

const useDaily = table('Use daily');
const adopted = table('Just adopted');
const skipped = table('Evaluated and skipped');

const md = `<!-- GENERATED by scripts/sync-sources.mjs from the hub's data/ai-tooling-audit.md.
     Do not edit by hand. Re-run \`npm run sync\` after the hub file changes. -->

# AI tooling audit, cleared tables

Last audited: ${clear(audited)}

## Use daily

| Tool | What it does in the workflow |
|---|---|
${useDaily.rows.map(([tool, what]) => `| ${clear(tool)} | ${clear(what)} |`).join('\n')}

## Just adopted

| Tool | Adopted | Why, and what is still unproven |
|---|---|---|
${adopted.rows.map(([tool, when, why]) => `| ${clear(tool)} | ${clear(when)} | ${clear(why)} |`).join('\n')}

## Evaluated and skipped

| Tool | When | Verdict and reason |
|---|---|---|
${skipped.rows.map(([tool, when, why]) => `| ${clear(tool)} | ${clear(when)} | ${clear(why)} |`).join('\n')}
`;

await mkdir(path.dirname(OUT), { recursive: true });
await writeFile(OUT, md);
console.log(`wrote ${path.relative(ROOT, OUT)} (audited ${audited}; ${useDaily.rows.length} daily, ${adopted.rows.length} adopted, ${skipped.rows.length} skipped)`);
if (/Notion|master doc \d|issue #\d/.test(md)) throw new Error('clearance leak: private reference survived');
